name: pycheck

on: [push]

jobs:
  pycheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GitHub Action for Python code check
        uses: nanato12/pycheck@master
        with:
          path: './'
